[tool.poetry]
name = "mongotoy"
version = "0.1.0"
description = ""
authors = ["gurcuff91 <gf.meneses91@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
motor = "^3.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
